name: 'My first github action'

# push 이벤트가 발생하면 작동
on: push

env:
  WORKFLOW_LEVEL: 'THIS VALUE COMES FROM THE WORKFLOW LEVEL' # workflow 단위로 참조 가능

jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_1: 'THIS VALUE COMES FROM JOB LEVEL 1' # job 단위에서 참조 가능

    steps:
    - name: mask value
      id: first
      shell: bash
      run: |
        first_value="This is the first output value"
        echo "::add-mask::$first_value"
        echo "::set-output name=my_first_value::$first_value"

    - name: get output value
      shell: bash
      run: |
        echo ${{ steps.first.outputs.my_first_value }}
        echo ${{ secrets.HELLO }}