name: 'My first github action'

# push 이벤트가 발생하면 작동
on: push

env:
  WORKFLOW_LEVEL: 'THIS VALUE COMES FROM THE WORKFLOW LEVEL' # workflow 단위로 참조 가능

jobs:
  first-job:
    name: 'first job'

    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']

    runs-on: ${{ matrix.os }}

    env:
      JOB_LEVEL_1: 'THIS VALUE COMES FROM JOB LEVEL 1' # job 단위에서 참조 가능

    steps:
    - name: output value from ${{ matrix.os }}
      id: first
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"