name: 'My first github action'

# 추천하지는 않는다. push에 사용할 yaml 하나, pull_request에 사용한 yaml 하나를 추천
on: ['push', 'pull_request']

env:
  WORKFLOW_LEVEL: 'THIS VALUE COMES FROM THE WORKFLOW LEVEL' # workflow 단위로 참조 가능

jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    - name: output value 1
      id: first
      shell: bash
      run: |
        echo "HELLO WORLD"
    
    - name: output value 2
      id: second
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        echo "HELLO WORLD"
  
  second-job:
    name: 'second job'
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    - name: output value from ubuntu-latest
      id: first
      shell: bash
      run: |
        echo "HELLO WORLD"