name: 'My first github action'

# push 이벤트가 발생하면 작동
on: push

env:
  WORKFLOW_LEVEL: 'THIS VALUE COMES FROM THE WORKFLOW LEVEL' # workflow 단위로 참조 가능

jobs:
  first-job:
    name: 'first job'

    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        nodejs: ['14.x', '16.x']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
       node-version: ${{ matrix.nodejs }}


    - name: output value from ${{ matrix.os }}
      id: first
      shell: bash
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "node.js: ${{ matrix.nodejs }}"